kind: ConfigMap
apiVersion: v1
metadata:
  name: debug-ansible
data:
  # GIT_USER: auth_user # optional
  # GIT_TOKEN: auth_token # optional
  # GIT_BRANCH: git_branch # optional
  GIT_REPO: https://github.com/dnum-mi/dso-playbooks.git
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug-ansible-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: "debug-ansible"
  namespace: default
  labels:
    app: "debug-ansible"
spec:
  serviceAccountName: debug-ansible-sa
  containers:
  - name: debug-ansible
    image: "debian-slim:latest"
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 200Mi
    envFrom:
    - configMapRef:
        name: debug-ansible
    volumeMounts:
    - name: playbooks
      mountPath: /dso/
  volumes:
  - name: playbooks
    emptyDir:
      sizeLimit: 1000M
  restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debug-clusterole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: debug-ansible-cluster-role
subjects:
- kind: ServiceAccount
  name: debug-ansible-sa
  namespace: openshift-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debug-ansible-cluster-role
rules:
- apiGroups:
  - ""
  - user.openshift.io
  - rbac.authorization.k8s.io
  - argoproj.io
  resources:
  - '*'
  verbs:
  - '*'